# vi: et ts=2 sts=2 sw=2 ai
---

kubernetes_disable_rp_filter: no
kubernetes_kubeadm_env: {}

primary_internal_iface: "{{ ansible_default_ipv4.interface }}"
kubernetes_node_ip: "{{ hostvars[inventory_hostname]['ansible_' ~ primary_internal_iface].ipv4.address }}"
kubernetes_master_ip: "{{ hostvars[groups['kubernetes'][0]]['ansible_' ~ primary_internal_iface].ipv4.address }}"
kubernetes_apiserver_advertise_address: "{{ kubernetes_master_ip }}"
kubernetes_apiserver_bind_port: 6443
kubernetes_apiserver_cert_extra_sans: kubernetes.example.com,kube.example.com,k8s.example.com
kubernetes_external_etcd_endpoints: "{% for host in groups['etcd'] %}http://{{ hostvars[host]['etcd_node_ip'] }}:{{ etcd_client_port }}{% if not loop.last %},{% endif %}{% endfor %}"
kubernetes_pod_network_cidr: 172.16.0.0/16
kubernetes_service_cidr: 172.31.0.0/16
kubernetes_cluster_dns: 172.31.0.10
kubernetes_cluster_domain: cluster.local

# https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/version.go#L33
# it can be stable, latest, stable-1, latest-1, stable-1.0, latest-1.0, ...
kubernetes_version: stable-1.6
kubeadm_version: 1.6.*
kubectl_version: 1.6.*
kubelet_version: 1.6.*
kubernetes_cni_version: "*"

etcd_client_port: 2379

kubeadm_extra_args: ""
#kubernetes_root_dir: /data0/var/lib/kubelet

