# vi: et ts=2 sts=2 sw=2 ai
---

kubernetes_disable_rp_filter: no

primary_internal_iface: "{{ ansible_default_ipv4.interface }}"
kubernetes_node_ip: "{{ hostvars[inventory_hostname]['ansible_' ~ primary_internal_iface].ipv4.address }}"
kubernetes_master_ip: "{{ hostvars[groups['kubernetes'][0]]['ansible_' ~ primary_internal_iface].ipv4.address }}"
kubernetes_apiserver_advertise_address: "{{ kubernetes_master_ip }}"
kubernetes_apiserver_bind_port: 6443
kubernetes_apiserver_cert_extra_sans: kubernetes.example.com,kube.example.com,k8s.example.com
kubernetes_external_etcd_endpoints: "{% for host in groups['etcd'] %}http://{{ hostvars[host]['etcd_node_ip'] }}:{{ etcd_client_port }}{% if not loop.last %},{% endif %}{% endfor %}"
kubernetes_pod_network_cidr: 172.16.0.0/16
kubernetes_service_cidr: 172.31.0.0/16
kubernetes_cluster_dns: 172.31.0.10
kubernetes_cluster_domain: cluster.local

# https://github.com/kubernetes/kubernetes/blob/master/cmd/kubeadm/app/util/version.go#L33
# it can be stable, latest, stable-1, latest-1, stable-1.0, latest-1.0, ...
kubernetes_version: stable-1.9
kubeadm_version: 1.9.*
kubectl_version: 1.9.*
kubelet_version: 1.9.*
kubernetes_cni_version: "*"

etcd_client_port: 2379

kubeadm_extra_args: ""
#kubernetes_root_dir: /data/var/lib/kubelet

kubelet_extra_args: >-
  --cgroup-driver cgroupfs
  --eviction-hard memory.available<5%,nodefs.available<10%,nodefs.inodesFree<5%,imagefs.available<10%,imagefs.inodesFree<5%
  --eviction-max-pod-grace-period 60
  --eviction-minimum-reclaim memory.available=200Mi,nodefs.available=500Mi,imagefs.available=2Gi
  --eviction-soft memory.available<10%,nodefs.available<15%,nodefs.inodesFree<10%,imagefs.available<15%,imagefs.inodesFree<10%
  --eviction-soft-grace-period memory.available=1m30s,nodefs.available=5m0s,nodefs.inodesFree=5m0s,imagefs.available=5m0s,imagefs.inodesFree=5m0s
  --eviction-pressure-transition-period 5m0s
  --node-status-update-frequency 10s
  --kube-reserved cpu=100m,memory=200Mi,ephemeral-storage=1Gi
  --system-reserved cpu=100m,memory=1Gi,ephemeral-storage=1Gi

kubernetes_apiserver_extra_args:
  audit-log-format: json
  audit-log-maxage: "10"
  audit-log-maxbackup: "10"
  audit-log-maxsize: "100"
  audit-log-path: /var/log/kubernetes/kube-audit.log
  audit-policy-file: /etc/kubernetes/audit-policy.yaml

