# vi: et ts=2 sts=2 sw=2 ai
---

- name: save /etc before all plays
  hosts: all

  tasks:
    - name: run apt update if etckeeper isn't installed
      shell: etckeeper --version >/dev/null 2>/dev/null || apt update

    - name: install package etckeeper
      apt: name=etckeeper state=present
      tags: etckeeper

    - name: run "etckeeper save" if necessary before all plays
      shell: chdir=/etc
             test -e .git || etckeeper init;
             git config --get user.name >/dev/null || git config user.name "root";
             git config --get user.email >/dev/null || git config user.email "root@localhost";
             ! etckeeper unclean || etckeeper commit "by Ansible before all plays";
      tags: etckeeper

